# -*- coding: utf-8 -*-
"""automate_Muna aliya zahra

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145CXKLjwHbdgCsMCIPUkmmtWNlusSwW2
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

def preprocess_smart_home(file_path, output_path):
    df = pd.read_csv(file_path)

    df = df.drop(columns=["UserID", "DeviceType_encoded"], errors='ignore')

    en = LabelEncoder()
    df["DeviceType"] = en.fit_transform(df["DeviceType"])

    X = df.drop(columns=["SmartHomeEfficiency"])
    y = df["SmartHomeEfficiency"]

    numeric_cols = X.select_dtypes(include=["int64", "float64"]).columns
    scaler = StandardScaler()
    X[numeric_cols] = scaler.fit_transform(X[numeric_cols])

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    sm = SMOTE(random_state=42)
    X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

    processed_data = pd.concat([X_train_res, y_train_res.reset_index(drop=True)], axis=1)
    processed_data.to_csv(output_path, index=False)
    print(f"Processed data saved to: {output_path}")

    return X_train_res, X_test, y_train_res, y_test

if __name__ == "__main__":
    input_file = "smart_home_device_usage_data.csv"
    output_file = "smart_home_processed.csv"
    X_train_res, X_test, y_train_res, y_test = preprocess_smart_home(input_file, output_file)