# -*- coding: utf-8 -*-
"""Template_Eksperimen_MSML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlFqxgQyUGhXz88OXsDQ05M1o2aiqhve

# **1. Perkenalan Dataset**

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset dapat diperoleh dari berbagai sumber, seperti public repositories (*Kaggle*, *UCI ML Repository*, *Open Data*) atau data primer yang Anda kumpulkan sendiri.

**Deskripsi**

Dataset ini berisi metrik penggunaan perangkat smart home yang memberikan wawasan tentang perilaku pengguna, efisiensi perangkat, dan preferensi penggunaan. Di dalamnya terdapat informasi mengenai jenis perangkat, pola penggunaan, konsumsi energi, insiden kerusakan, serta tingkat kepuasan pengguna.

**penjelasa fitur**

* UserID: Identitas unik untuk setiap pengguna.
* DeviceType: Jenis perangkat smart home
* UsageHoursPerDay: Rata-rata durasi penggunaan perangkat per hari
* EnergyConsumption: Konsumsi energi harian perangkat (dalam kWh).
* UserPreferences: Preferensi pengguna terhadap penggunaan perangkat(0 = Low, 1 = High)
* MalfunctionIncidents: Jumlah insiden kerusakan yang dilaporkan
* DeviceAgeMonths: Usia perangkat dalam bulan.
* SmartHomeEfficiency (Variabel Target): Status efisiensi perangkat smart home
(0 = Inefficient, 1 = Efficient).

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

"""# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan
"""

#Type your code here
df = pd.read_csv("/content/smart_home_device_usage_data.csv")

df.head(5)

"""# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.
"""

#Type your code here
df.info()

df.shape

df.columns

df.describe()

df.isnull().sum()

df.duplicated().sum()

plt.figure(figsize=(6,4))
sns.countplot(x="SmartHomeEfficiency", data=df)
plt.title("Distribusi Efisiensi Smart Home")
plt.xlabel("SmartHomeEfficiency (0 = Inefficient, 1 = Efficient)")
plt.ylabel("Jumlah")
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(x="DeviceType", data=df)
plt.title("Distribusi Jenis Perangkat")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(7,4))
sns.histplot(df["UsageHoursPerDay"], kde=True)
plt.title("Distribusi Jam Pemakaian per Hari")
plt.show()

plt.figure(figsize=(7,4))
sns.histplot(df["EnergyConsumption"], kde=True)
plt.title("Distribusi Konsumsi Energi (kWh)")
plt.show()

le1 = LabelEncoder()
df['DeviceType_encoded'] = le1.fit_transform(df['DeviceType'])

numeric_df = df.select_dtypes(include=['int64', 'float64'])
plt.figure(figsize=(10,6))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Korelasi Antar Fitur Numerik")
plt.show()

num_cols = ["UsageHoursPerDay", "EnergyConsumption", "MalfunctionIncidents", "DeviceAgeMonths","UserPreferences"]

plt.figure(figsize=(12,10))
for i, col in enumerate(num_cols, 1):
    plt.subplot(3, 2, i)
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot {col}")

plt.tight_layout()
plt.show()

plt.figure(figsize=(7,4))
sns.boxplot(x="SmartHomeEfficiency", y="EnergyConsumption", data=df)
plt.title("Perbandingan Konsumsi Energi berdasarkan Efisiensi")
plt.show()

sns.boxplot(x="SmartHomeEfficiency", y="UsageHoursPerDay", data=df)
plt.title("Perbandingan usagehours berdasarkan efisiensi")
plt.show()

sns.boxplot(x="SmartHomeEfficiency", y="MalfunctionIncidents", data=df)
plt.title("Perbandingan MalfunctionIncidents berdasarkan efisiensi")
plt.show()

sns.boxplot(x="SmartHomeEfficiency", y="DeviceAgeMonths", data=df)
plt.title("Perbandingan deviceage berdasarkan Efisiensi")
plt.show()

plt.figure(figsize=(8,4))
sns.barplot(x="DeviceType", y="SmartHomeEfficiency", data=df)
plt.title("Rata-rata Efisiensi Berdasarkan Jenis Perangkat")
plt.xticks(rotation=45)
plt.show()

"""# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.
"""

for col in df.columns:
    print(f"\n{col} ({df[col].nunique()} unique):")
    print(df[col].unique()[:10])

numeric_cols = df.select_dtypes(include=np.number).columns
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(f"{col}: {len(outliers)} outliers")

df = df.drop(columns=["UserID","DeviceType_encoded"])

df.head()

en = LabelEncoder()
df["DeviceType"] = en.fit_transform(df["DeviceType"])
df.head()

X = df.drop(columns=["SmartHomeEfficiency"])
y = df["SmartHomeEfficiency"]

print("Target distribution:")
print(y.value_counts())

numeric_cols = X.select_dtypes(include=["int64", "float64"]).columns
scaler = StandardScaler()
X[numeric_cols] = scaler.fit_transform(X[numeric_cols])

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)
print("Train class distribution:")
print(y_train.value_counts())

sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

print("After SMOTE:")
print(y_train_res.value_counts())